import { Geist, Geist_Mono } from "next/font/google"
import Navbar from '../components/Navbar'
import API from '../lib/api'
import { SocketProvider } from '../context/SocketContext'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Aurelia Residence",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <head />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        <SocketProvider>
          {children}
        </SocketProvider>
      </body>
    </html>
  )
}
